%YAML:1.0 # need to specify the file type at the top!

lidar:
  enabled: true
  max_n: 1
  do_calib_dt: true
  do_calib_ext: true
  init_cov_dt: 1e-4
  init_cov_ex_o: 1e-6
  init_cov_ex_p: 1e-6
  max_range: 12.0
  min_range: 0.045
  chi2_mult: 1
  raw_do_downsample: true
  raw_downsample_size: 1.0
  raw_noise: 0.1
  raw_remove_motion_blur: false # required to set v_angles and h_angles correctly
  raw_point_dt: 1e-6
  map_do_downsample: true
  map_downsample_size: 0.3
  map_noise: 0.1
  map_ngbr_num: 5
  map_ngbr_max_d: 12.0
  map_decay_time: 9999 # sec
  map_decay_dist: 12 # m
  map_use_icp: false
  map_icp_dist: 12 # m
  plane_max_p2pd: 0.1
  plane_max_condi: 200.0

lidar0:
  timeoffset: -0.0
  T_imu_lidar:
    - [-0.514521, 0.701075, -0.493723, -0.333596]
    - [ -0.492472, -0.712956, -0.499164,-0.373928]
    - [ -0.701954, -0.0136853, 0.712091 ,1.94377]
    - [0.0, 0.0, 0.0, 1.0]
  topic: "/scan"
